name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

 - name: Get Docker image size
      id: image_size
      run: |
        IMAGE_SIZE=$(docker image inspect ${{ secrets.ACR_LOGIN_SERVER }}/my-app:latest --format='{{.Size}}')
        IMAGE_SIZE_MB=$(echo "$IMAGE_SIZE / 1048576" | bc)
        echo "Image size: $IMAGE_SIZE_MB MB"
        echo "::set-output name=size::$IMAGE_SIZE_MB"

    - name: Print Docker image size
      run: echo "The Docker image size is ${{ steps.image_size.outputs.size }} MB"
