name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      id: build_image
      run: |
        IMAGE_NAME="test:v1"
        docker build -t $IMAGE_NAME .
        IMAGE_SIZE=$(docker image inspect $IMAGE_NAME --format='{{.Size}}')
        IMAGE_SIZE_MB=$(echo "$IMAGE_SIZE / 1048576" | bc)
        echo "Image size: $IMAGE_SIZE_MB MB"
        echo "::set-output name=size::$IMAGE_SIZE_MB"

    - name: Print Docker image size
      run: echo "The Docker image size is ${{ steps.build_image.outputs.size }} MB"
